### PR TITLE
Issue 17: Added BodyPart::Raw

### PR DESCRIPTION
**Pull request by mdsimmo**
Implement issue #17

This will be a breaking change to the API

### CODE REVIEW

**Comment by lemunozm** [comment]
What's the state of this PR? I'm in the same situation as @mdsimmo

**Comment by mdecimus** [comment]
@lemunozm There is no need to add a bodypart raw, you can accomplish this using the existing API.

**Comment by jeremija** [comment]
I might be missing something, but with the `BodyType::Binary` there's no way to insert an unmodified part of the message that was already previously built because it will always try to . This is needed for PGP signing as described in [RFC2015 Section 5](https://www.rfc-editor.org/rfc/rfc2015#section-5):

```
     From: Michael Elkins <elkins@aero.org>
     To: Michael Elkins <elkins@aero.org>
     Mime-Version: 1.0
     Content-Type: multipart/signed; boundary=bar; micalg=pgp-md5;
     protocol="application/pgp-signature"

     --bar
     & Content-Type: text/plain; charset=iso-8859-1
     & Content-Transfer-Encoding: quoted-printable
     &
     & =A1Hola!
     &
     & Did you know that talking to yourself is a sign of senility?
     &
     & It's generally a good idea to encode lines that begin with
     & From=20because some mail transport agents will insert a greater-
     & than (>) sign, thus invalidating the signature.
     &
     & Also, in some cases it might be desirable to encode any   =20
     &railing whitespace that occurs on lines in order to ensure  =20
     & that the message signature is not invalidated when passing =20
     & a gateway that modifies such whitespace (like BITNET). =20
     &
     & me

     --bar
     Content-Type: application/pgp-signature

    -----BEGIN PGP MESSAGE-----
   Version: 2.6.2

   iQCVAwUBMJrRF2N9oWBghPDJAQE9UQQAtl7LuRVndBjrk4EqYBIb3h5QXIX/LC//
   jJV5bNvkZIGPIcEmI5iFd9boEgvpirHtIREEqLQRkYNoBActFBZmh9GC3C041WGq
   uMbrbxc+nIs1TIKlA08rVi9ig/2Yh7LFrK5Ein57U/W72vgSxLhe/zhdfolT9Brn
   HOxEa44b+EI=
   =ndaj
   -----END PGP MESSAGE-----

   --bar--

   The "&"s in the previous example indicate the portion of the data
   over which the signature was calculated.
```

The existing code currently results in the `Content-Transfer-Encoding` header being written and the data converted into base64, making the e-mail look weird and the signature validation fail.

https://github.com/stalwartlabs/mail-builder/blob/e771643f2f4ff8ea86f91f7985b1efa6ffa8aa85/src/mime.rs#L267-L272

My code currently builds an `inner` MIME message, builds a string out of it and then PGP signs it. And then I'd like to inject the inner message without modifications into the outer message which contains the signature (see example above).

Is there a better approach to doing this?

**Comment by mdecimus** [comment]
Are you trying to insert the raw headers as well or just the ascii-armored part generated by OpenPGP?

**Comment by mdecimus** [comment]
Please try using the version `0.3.1` from the repository, it contains a new method `MimePart::transfer_encoding` that you can use to disable automatic `Content-Transfer-Encoding` detection and include the part as is.

**Comment by jeremija** [comment]
I took a look at the code, but I don't think this would work because the `Content-Transfer-Encoding` header is still being written after `is_raw` is set to true.

```diff
+                            } else if !is_raw && header_name == "Content-Transfer-Encoding" {
+                                is_raw = true;
                             }
                             header_value.write_header(&mut output, header_name.len() + 2)?;
                         }
-                        detect_encoding(text.as_bytes(), &mut output, !is_attachment)?;
+                        if !is_raw {
+                            detect_encoding(text.as_bytes(), &mut output, !is_attachment)?;
+                        } else {
+                            output.write_all(b"\r\n")?;
+                            output.write_all(text.as_bytes())?;
+                        }
```

For the record, I've had success with @mdsimmo's branch in #17 (rebased to `main`) where I've used it like this:

```rust
let mut signed = MimePart::new("", BodyPart::Raw(Cow::Owned(inner_str.into_bytes())));
// Remove the Content-Type header as we want the signed part to be written
// without any modifications so the signature verification can pass. It
// should already be in the correct form by now.
signed.headers.clear();

outer.body(
    MimePart::new(
        ContentType::new("multipart/signed")
            .attribute("protocol", "application/pgp-signature")
            .attribute("micalg", sign.algorithm_symbol()),
        vec![
            signed,
            MimePart::new("application/pgp-signature", pgp_data),
        ],
    ),
)
```

**Comment by mdecimus** [comment]
> I took a look at the code, but I don't think this would work because the Content-Transfer-Encoding header is still being written after is_raw is set to true.

That is correct, if you provide your own `Content-Transfer-Encoding` header the header is written but also automatic detection is disabled and the contents are included as they are. You can try something like this:

```rust
    MimePart::new(
        ContentType::new("multipart/signed")
            .attribute("protocol", "application/pgp-signature")
            .attribute("micalg", sign.algorithm_symbol()),
        vec![
            MimePart::new("text/plain", original_message).transfer_encoding("8bit"), // Or quoted-printable if you have already encoded the contents
            MimePart::new("application/pgp-signature", pgp_data).transfer_encoding("7bit"),
        ],
    )
```

**Comment by jeremija** [comment]
Thanks, but if a new header is injected it means the signature validation will fail because it won't adhere to the RFC I wrote about above.

In your example we'll end up with a tree of:

- `multipart/signed`
  - `text/plain`
  - `application/pgp-signed`

The `text/plain` node will have an extra `Content-Type` and  `Content-Transfer-Encoding` headers, while the originally signed message did not have them.

Also, there's no guarantee that it will be `text/plain` as it could be html or multipart (combination of text/html, or even attachments). In my case all of this is already present in raw data since I'm passing down a string generated from a separate instance of `MessageBuilder`.

**Comment by mdecimus** [comment]
The example I provided is when you provide the contents already encoded. Now that you mentioned multiple headers I understand that you are trying to add an entire part including raw headers. That is currently not possible but I'll quickly add a Raw type now.

**Comment by mdecimus** [comment]
Done, now you can add your raw part including headers using `MimePart::raw(inner_str)`

**Comment by jeremija** [comment]
Thanks so much for adding it so quickly!

I ran some tests and indeed it seems to work, the final problem seems to be in the fact that this library adds multiple line breaks in multipart emails which then disappear after sending, which again render the signature invalid.

The issue seems to be related to this line: https://github.com/stalwartlabs/mail-builder/blob/1eb0b5a72211c491cbe338920e8dfd3a675d6653/src/mime.rs#L376

and I see that @mdsimmo has already fixed it in their fork in: https://github.com/mdsimmo/mail-builder/commit/d250d4d9d398959e340e534fc9ab18350985fc2a

That said, I think the issue might actually be caused by my email provder (Mailgun) or any server in between mailgun and Gmail. A double `\r\n\r\n`  sequence is converted into a single `\r\n` in between the multipart boundaries, so no data is altered, but it unfortunately this renders the PGP signature invalid. I'm not sure if the spec says anything about such lines. If you wish, I can provide a more detailed example tomorrow.

**Comment by jeremija** [comment]
After taking a deeper look into this, I'm not sure if `mail-builder` is to blame for these extra line breaks as they messages seem formatted in the same way as the examples in [RFC 1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).  But I'm still not sure how the duplicates end up getting removed in the received e-mail, this must be some re-formatting done by Mailgun before the e-mail is sent, as modifying it later would break DKIM.

Here's a detailed example:

<details>

<summary>main.rs</summary>

```rust
use mail_builder::MessageBuilder;
use mail_builder::headers::content_type::ContentType;
use mail_builder::mime::MimePart;

fn main() {
    let inner = MessageBuilder::new()
        .message_id("123")
        .from(("John Doe", "john@doe.com"))
        .to("jane@doe.com")
        .subject("Hello, world!")
        .attachment("text/plain", "file1.txt", "some text")
        .text_body("hello there")
        .write_to_string()
        .unwrap();

    let pgp_signature = "TODO sign inner";

    let eml = MessageBuilder::new()
        .message_id("123")
        .from(("John Doe", "john@doe.com"))
        .to("jane@doe.com")
        .subject("Hello, world!")
        .body(
            MimePart::new(
                ContentType::new("multipart/signed")
                    .attribute("protocol", "application/pgp-signature")
                    .attribute("micalg", "sha1"),
                vec![
                    MimePart::raw(inner.into_bytes()),
                    MimePart::new("application/pgp-signature", pgp_signature),
                ],
            ),
        )
        .write_to_string()
        .unwrap();

    print!("{}", eml);
}
```

</details>

<details>

<summary>output of `cargo run | cat -te`</summary>

```
Message-ID: <123>^M$
From: "John Doe" <john@doe.com>^M$
To: <jane@doe.com>^M$
Subject: Hello, world!^M$
Date: Mon, 7 Aug 2023 07:25:32 +0000^M$
Content-Type: multipart/signed; protocol="application/pgp-signature"; ^M$
^Imicalg="sha1"; ^M$
^Iboundary="17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050"^M$
^M$
^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050^M$
Message-ID: <123>^M$
From: "John Doe" <john@doe.com>^M$
To: <jane@doe.com>^M$
Subject: Hello, world!^M$
Date: Mon, 7 Aug 2023 07:25:32 +0000^M$
Content-Type: multipart/mixed; ^M$
^Iboundary="17790917a6d32899_b1b10295130e8690_f141503009d8c050"^M$
^M$
^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050^M$
Content-Type: text/plain; charset="utf-8"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
hello there^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050^M$
Content-Type: text/plain; charset="utf-8"^M$
Content-Disposition: attachment; filename="file1.txt"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
some text^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050--^M$
^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050^M$
Content-Type: application/pgp-signature; charset="utf-8"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
TODO sign inner^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050--^M$
```

</details>

However what I end up getting receiving is this:


<details>

<summary>received.txt</summary>

```
Message-ID: <123>^M$
From: "John Doe" <john@doe.com>^M$
To: <jane@doe.com>^M$
Subject: Hello, world!^M$
Date: Mon, 7 Aug 2023 07:25:32 +0000^M$
Content-Type: multipart/signed; protocol="application/pgp-signature"; ^M$
^Imicalg="sha1"; ^M$
^Iboundary="17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050"^M$
^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050^M$
Message-ID: <123>^M$
From: "John Doe" <john@doe.com>^M$
To: <jane@doe.com>^M$
Subject: Hello, world!^M$
Date: Mon, 7 Aug 2023 07:25:32 +0000^M$
Content-Type: multipart/mixed; ^M$
^Iboundary="17790917a6d32899_b1b10295130e8690_f141503009d8c050"^M$
^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050^M$
Content-Type: text/plain; charset="utf-8"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
hello there^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050^M$
Content-Type: text/plain; charset="utf-8"^M$
Content-Disposition: attachment; filename="file1.txt"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
some text^M$
--17790917a6d32899_b1b10295130e8690_f141503009d8c050--^M$
^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050^M$
Content-Type: application/pgp-signature; charset="utf-8"^M$
Content-Transfer-Encoding: 7bit^M$
^M$
TODO sign inner^M$
--17790917a6d4c7e1_4fe87c4e925902a5_f141503009d8c050--^M$

```

</details>

Diff:

```diff
10d9
< ^M$
19d17
< ^M$
```

And this makes the signature invalid, since the inner contents were modified after the signature was made.

**Comment by mdecimus** [comment]
Yes, it looks like your MTA is reformatting the message. This behavior could also break DKIM and ARC signatures. If you send the message via Gmail or a different MTA does it work?

**Comment by jeremija** [comment]
I don't have the ability to test using a different MTA at this moment, but I'll open a support ticket with Mailgun. I have a good way to reproduce this.

However, upon writing the aforementioned support ticket, I noticed this paragraph in the [RFC 1341](https://www.rfc-editor.org/rfc/rfc1341]) Section 7.2 (Multipart:  The common syntax):

> The requirement that the encapsulation boundary begins with a CRLF implies that the body of a multipart entity must itself begin with a CRLF before the first encapsulation line -- that is, **if the "preamble" area is not used, the entity headers must be followed by TWO CRLFs**. This is indeed how such entities should be composed. A tolerant mail reading program, however, may interpret a body of type multipart that begins with an encapsulation line NOT initiated by a CRLF as also being an encapsulation boundary, but a compliant mail sending program must not generate such entities.

but in the example I posted about above, we have _three_ of them:

```eml
Content-Type: multipart/mixed; ^M$
^Iboundary="17790917a6d32899_b1b10295130e8690_f141503009d8c050"^M$ <-- one
^M$                                                                <-- two
^M$                                                                <-- three
--17790917a6d32899_b1b10295130e8690_f141503009d8c050^M$
```

so perhaps it would make sense to address this in this library in order to completely follow the RFC?

**Comment by jeremija** [comment]
I just learned that there's a newer RFC 2045 which is less specific about the newlines in preamble (the paragraph I quoted was removed), but the examples look different (noticed how the newer example only has two CRLFs before the boundary):

[RFC 1341](https://www.rfc-editor.org/rfc/rfc1341.txt)

```eml
            From: Moderator-Address
            MIME-Version: 1.0
            Subject:  Internet Digest, volume 42
            Content-Type: multipart/digest;
                 boundary="---- next message ----"


            ------ next message ----
```

[RFC 2046](https://www.rfc-editor.org/rfc/rfc2046.txt)

```eml
     From: Moderator-Address
     To: Recipient-List
     Date: Mon, 22 Mar 1994 13:34:51 +0000
     Subject: Internet Digest, volume 42
     MIME-Version: 1.0
     Content-Type: multipart/mixed;
                   boundary="---- main boundary ----"

     ------ main boundary ----
```

**Comment by jeremija** [comment]
Thsnks @mdecimus, appreciate it! I realize this, especially because the preable content can basically be anything as explained in the RFC

I have opened a ticket with Mailgun, just got two follow ups that they are still looking into it. Will keep you posted

**Pull request closed without merging**
